services:
#  stats-server:
#    container_name: stats-server
#    build: stats/stats-server
#    ports:
#      - "9090:9090"
#    depends_on:
#      stats-db:
#        condition: service_healthy
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
#      - SPRING_DATASOURCE_USERNAME=dbuser
#      - SPRING_DATASOURCE_PASSWORD=12345
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:9090/actuator/health"]
#      interval: 10s
#      timeout: 5s
#      retries: 10

  stats-db:
    image: postgres:16.1
    container_name: postgres-stats-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

#  ewm-service:
#    container_name: emw-service
#    build:
#      context: main-service
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    depends_on:
#      main-db:
#        condition: service_healthy
#      stats-server:
#        condition: service_healthy
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/main-db
#      - SPRING_DATASOURCE_USERNAME=dbuser
#      - SPRING_DATASOURCE_PASSWORD=12345
#      - STATS_SERVER_URL=http://stats-server:9090

  main-db:
    image: postgres:16.1
    container_name: postgres-main-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=main-db
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10